### PR TITLE
adding dark theme

### PR DESCRIPTION
**Pull request by pauloricardokoch**

### CODE REVIEW

**Comment by tcarreira** [comment]
@pauloricardokoch did you include yarn.lock on purpose?

**Review by tcarreira — APPROVED** [review]

**Review by tcarreira — CHANGES_REQUESTED** [review]
is yarn.lock supposed to be here?

**Comment by pauloricardokoch** [comment]
> is yarn.lock supposed to be here?

Hey Tiago,

When you ask if it is supposed to be here, do you mean on this commit or in the project?

I've updated it so I wouldn't get this error when running the app.
```code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'```

It might be related to some issue with my setup, so I reverted it.

**Comment by tcarreira** [comment]
> When you ask if it is supposed to be here, do you mean on this commit or in the project?

Yes, on this commit.
Based on the previous repo history, I believe the intention is having just the package.json dependencies, but not the yarn.lock.

I might be wrong too 😅
I'm sure @marcelometal could confirm that. 

I'm just asking because it was never mentioned.

I any case, I think including the yarn.lock should be an a different commit.

**Comment by marcelometal** [comment]
Thank you @pauloricardokoch !

**Pull request merged**
